version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            . venv/bin/activate
            jupyter-nbconvert --execute main.ipynb
            mkdir -p res
            mv main.html res/
      - store_artifacts:
          path: res/
          destination: res/